// Generated by tools/generate_battle_frontier_from_competitive_json.py.
static const struct FrontierBrainMon sFrontierBrainsMons[][2][FRONTIER_PARTY_SIZE] =
{
    [FRONTIER_FACILITY_TOWER] =
    {
        // Silver Symbol.
        {
            {
                .species = SPECIES_KINGAMBIT,
                .heldItem = ITEM_CHOPLE_BERRY,
                .fixedIV = 24,
                .nature = NATURE_ADAMANT,
                .evs = {252, 252, 0, 4, 0, 0},
                .moves = {MOVE_SUCKER_PUNCH, MOVE_KOWTOW_CLEAVE, MOVE_PROTECT, MOVE_IRON_HEAD},
            },
            {
                .species = SPECIES_GARCHOMP,
                .heldItem = ITEM_LIFE_ORB,
                .fixedIV = 24,
                .nature = NATURE_JOLLY,
                .evs = {4, 252, 0, 252, 0, 0},
                .moves = {MOVE_DRAGON_CLAW, MOVE_EARTHQUAKE, MOVE_ROCK_SLIDE, MOVE_PROTECT},
            },
            {
                .species = SPECIES_SINISTCHA,
                .heldItem = ITEM_COLBUR_BERRY,
                .fixedIV = 24,
                .nature = NATURE_BOLD,
                .evs = {252, 0, 100, 0, 0, 156},
                .moves = {MOVE_MATCHA_GOTCHA, MOVE_RAGE_POWDER, MOVE_PROTECT, MOVE_TRICK_ROOM},
            },
        },
        // Gold Symbol.
        {
            {
                .species = SPECIES_MEWTWO,
                .heldItem = ITEM_MEWTWONITE_Y,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_TIMID,
                .evs = {0, 0, 88, 216, 204, 0},
                .moves = {MOVE_NASTY_PLOT, MOVE_PSYSTRIKE, MOVE_FIRE_BLAST, MOVE_ICE_BEAM},
            },
            {
                .species = SPECIES_ZACIAN_CROWNED,
                .heldItem = ITEM_RUSTED_SWORD,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_JOLLY,
                .evs = {0, 252, 4, 252, 0, 0},
                .moves = {MOVE_SWORDS_DANCE, MOVE_BEHEMOTH_BLADE, MOVE_WILD_CHARGE, MOVE_CLOSE_COMBAT},
            },
            {
                .species = SPECIES_KYOGRE,
                .heldItem = ITEM_CHOICE_SPECS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_MODEST,
                .evs = {248, 0, 0, 44, 216, 0},
                .moves = {MOVE_SURF, MOVE_WATER_SPOUT, MOVE_ICE_BEAM, MOVE_THUNDER},
            },
        },
    },
    [FRONTIER_FACILITY_DOME] =
    {
        // Silver Symbol.
        {
            {
                .species = SPECIES_CHARIZARD,
                .heldItem = ITEM_CHARIZARDITE_Y,
                .fixedIV = 20,
                .nature = NATURE_MODEST,
                .evs = {252, 0, 4, 0, 252, 0},
                .moves = {MOVE_HEAT_WAVE, MOVE_PROTECT, MOVE_WEATHER_BALL, MOVE_SOLAR_BEAM},
            },
            {
                .species = SPECIES_SWAMPERT,
                .heldItem = ITEM_SWAMPERTITE,
                .fixedIV = 20,
                .nature = NATURE_ADAMANT,
                .evs = {4, 252, 0, 252, 0, 0},
                .moves = {MOVE_PROTECT, MOVE_WAVE_CRASH, MOVE_EARTHQUAKE, MOVE_ICE_PUNCH},
            },
            {
                .species = SPECIES_METAGROSS,
                .heldItem = ITEM_METAGROSSITE,
                .fixedIV = 20,
                .nature = NATURE_JOLLY,
                .evs = {4, 252, 0, 252, 0, 0},
                .moves = {MOVE_PSYCHIC_FANGS, MOVE_PROTECT, MOVE_IRON_HEAD, MOVE_ICE_PUNCH},
            },
        },
        // Gold Symbol.
        {
            {
                .species = SPECIES_KORAIDON,
                .heldItem = ITEM_HEAVY_DUTY_BOOTS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_JOLLY,
                .evs = {0, 252, 4, 252, 0, 0},
                .moves = {MOVE_SWORDS_DANCE, MOVE_LOW_KICK, MOVE_OUTRAGE, MOVE_FLAME_CHARGE},
            },
            {
                .species = SPECIES_MIRAIDON,
                .heldItem = ITEM_LIFE_ORB,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_MODEST,
                .evs = {160, 0, 4, 92, 252, 0},
                .moves = {MOVE_AGILITY, MOVE_ELECTRO_DRIFT, MOVE_SOLAR_BEAM, MOVE_DRAGON_PULSE},
            },
            {
                .species = SPECIES_RAYQUAZA,
                .heldItem = ITEM_CHOICE_BAND,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_JOLLY,
                .evs = {32, 252, 8, 216, 0, 0},
                .moves = {MOVE_DRAGON_ASCENT, MOVE_U_TURN, MOVE_V_CREATE, MOVE_EXTREME_SPEED},
            },
        },
    },
    [FRONTIER_FACILITY_PALACE] =
    {
        // Silver Symbol.
        {
            {
                .species = SPECIES_ARCANINE_HISUI,
                .heldItem = ITEM_FOCUS_SASH,
                .fixedIV = 16,
                .nature = NATURE_JOLLY,
                .evs = {4, 252, 0, 252, 0, 0},
                .moves = {MOVE_FLARE_BLITZ, MOVE_PROTECT, MOVE_HEAD_SMASH, MOVE_EXTREME_SPEED},
            },
            {
                .species = SPECIES_SLOWKING_GALAR,
                .heldItem = ITEM_ASSAULT_VEST,
                .fixedIV = 16,
                .nature = NATURE_CALM,
                .evs = {252, 0, 0, 4, 0, 252},
                .moves = {MOVE_FUTURE_SIGHT, MOVE_SLUDGE_BOMB, MOVE_ACID_SPRAY, MOVE_EARTHQUAKE},
            },
            {
                .species = SPECIES_MILOTIC,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = 16,
                .nature = NATURE_CALM,
                .evs = {252, 0, 212, 4, 0, 40},
                .moves = {MOVE_PROTECT, MOVE_SCALD, MOVE_ICY_WIND, MOVE_ICE_BEAM},
            },
        },
        // Gold Symbol.
        {
            {
                .species = SPECIES_HO_OH,
                .heldItem = ITEM_HEAVY_DUTY_BOOTS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_ADAMANT,
                .evs = {252, 252, 0, 4, 0, 0},
                .moves = {MOVE_SACRED_FIRE, MOVE_BRAVE_BIRD, MOVE_RECOVER, MOVE_EARTHQUAKE},
            },
            {
                .species = SPECIES_LUGIA,
                .heldItem = ITEM_HEAVY_DUTY_BOOTS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_TIMID,
                .evs = {248, 0, 8, 252, 0, 0},
                .moves = {MOVE_CALM_MIND, MOVE_AIR_SLASH, MOVE_EARTH_POWER, MOVE_RECOVER},
            },
            {
                .species = SPECIES_GIRATINA,
                .heldItem = ITEM_HEAVY_DUTY_BOOTS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_IMPISH,
                .evs = {252, 0, 252, 0, 0, 4},
                .moves = {MOVE_DRAGON_TAIL, MOVE_WILL_O_WISP, MOVE_DEFOG, MOVE_REST},
            },
        },
    },
    [FRONTIER_FACILITY_ARENA] =
    {
        // Silver Symbol.
        {
            {
                .species = SPECIES_HERACROSS,
                .heldItem = ITEM_HERACRONITE,
                .fixedIV = 20,
                .nature = NATURE_ADAMANT,
                .evs = {252, 140, 0, 0, 0, 116},
                .moves = {MOVE_CLOSE_COMBAT, MOVE_PIN_MISSILE, MOVE_ROCK_BLAST, MOVE_DETECT},
            },
            {
                .species = SPECIES_KOMMO_O,
                .heldItem = ITEM_LIFE_ORB,
                .fixedIV = 20,
                .nature = NATURE_MODEST,
                .evs = {4, 0, 0, 252, 252, 0},
                .moves = {MOVE_CLANGING_SCALES, MOVE_PROTECT, MOVE_AURA_SPHERE, MOVE_VACUUM_WAVE},
            },
            {
                .species = SPECIES_BRELOOM,
                .heldItem = ITEM_FOCUS_SASH,
                .fixedIV = 20,
                .nature = NATURE_ADAMANT,
                .evs = {4, 252, 0, 252, 0, 0},
                .moves = {MOVE_BULLET_SEED, MOVE_MACH_PUNCH, MOVE_BULLDOZE, MOVE_SPORE},
            },
        },
        // Gold Symbol.
        {
            {
                .species = SPECIES_MARSHADOW,
                .heldItem = ITEM_LIFE_ORB,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_JOLLY,
                .evs = {0, 252, 4, 252, 0, 0},
                .moves = {MOVE_SPECTRAL_THIEF, MOVE_POLTERGEIST, MOVE_LOW_KICK, MOVE_SHADOW_SNEAK},
            },
            {
                .species = SPECIES_ZAMAZENTA_CROWNED,
                .heldItem = ITEM_RUSTED_SHIELD,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_JOLLY,
                .evs = {248, 0, 68, 192, 0, 0},
                .moves = {MOVE_IRON_DEFENSE, MOVE_BODY_PRESS, MOVE_BEHEMOTH_BASH, MOVE_SUBSTITUTE},
            },
            {
                .species = SPECIES_URSHIFU,
                .heldItem = ITEM_CHOICE_BAND,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_ADAMANT,
                .evs = {0, 252, 4, 252, 0, 0},
                .moves = {MOVE_WICKED_BLOW, MOVE_CLOSE_COMBAT, MOVE_SUCKER_PUNCH, MOVE_U_TURN},
            },
        },
    },
    [FRONTIER_FACILITY_FACTORY] =
    {
        // Silver Symbol.
        {
            {
                .species = SPECIES_METAGROSS,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_ADAMANT,
                .evs = {252, 28, 0, 188, 0, 40},
                .moves = {MOVE_PSYCHIC_FANGS, MOVE_BULLET_PUNCH, MOVE_ICE_PUNCH, MOVE_PSYCH_UP},
            },
            {
                .species = SPECIES_SKARMORY,
                .heldItem = ITEM_ROCKY_HELMET,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_BOLD,
                .evs = {252, 0, 160, 96, 0, 0},
                .moves = {MOVE_SPIKES, MOVE_ROOST, MOVE_BODY_PRESS, MOVE_IRON_DEFENSE},
            },
            {
                .species = SPECIES_AGGRON,
                .heldItem = ITEM_AGGRONITE,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_CAREFUL,
                .evs = {252, 4, 0, 0, 0, 252},
                .moves = {MOVE_PROTECT, MOVE_BODY_PRESS, MOVE_HEAVY_SLAM, MOVE_IRON_DEFENSE},
            },
        },
        // Gold Symbol.
        {
            {
                .species = SPECIES_METAGROSS,
                .heldItem = ITEM_METAGROSSITE,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_JOLLY,
                .evs = {4, 252, 0, 252, 0, 0},
                .moves = {MOVE_PSYCHIC_FANGS, MOVE_PROTECT, MOVE_IRON_HEAD, MOVE_ICE_PUNCH},
            },
            {
                .species = SPECIES_SKARMORY,
                .heldItem = ITEM_ROCKY_HELMET,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_BOLD,
                .evs = {252, 0, 252, 0, 0, 4},
                .moves = {MOVE_BODY_PRESS, MOVE_WHIRLWIND, MOVE_SPIKES, MOVE_ROOST},
            },
            {
                .species = SPECIES_AGGRON,
                .heldItem = ITEM_AGGRONITE,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_CAREFUL,
                .evs = {252, 4, 0, 0, 0, 252},
                .moves = {MOVE_PROTECT, MOVE_BODY_PRESS, MOVE_HEAVY_SLAM, MOVE_IRON_DEFENSE},
            },
        },
    },
    [FRONTIER_FACILITY_PIKE] =
    {
        // Silver Symbol.
        {
            {
                .species = SPECIES_SEVIPER,
                .heldItem = ITEM_LIFE_ORB,
                .fixedIV = 16,
                .nature = NATURE_JOLLY,
                .evs = {0, 252, 0, 252, 0, 4},
                .moves = {MOVE_SUCKER_PUNCH, MOVE_EARTHQUAKE, MOVE_FLAMETHROWER, MOVE_GIGA_DRAIN},
            },
            {
                .species = SPECIES_MILOTIC,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = 16,
                .nature = NATURE_CALM,
                .evs = {252, 0, 212, 4, 0, 40},
                .moves = {MOVE_PROTECT, MOVE_SCALD, MOVE_ICY_WIND, MOVE_ICE_BEAM},
            },
            {
                .species = SPECIES_GLIMMORA,
                .heldItem = ITEM_GLIMMORANITE,
                .fixedIV = 16,
                .nature = NATURE_MODEST,
                .evs = {4, 0, 0, 252, 252, 0},
                .moves = {MOVE_POWER_GEM, MOVE_SLUDGE_BOMB, MOVE_EARTH_POWER, MOVE_SPIKY_SHIELD},
            },
        },
        // Gold Symbol.
        {
            {
                .species = SPECIES_ZYGARDE,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_IMPISH,
                .evs = {252, 0, 252, 0, 0, 4},
                .moves = {MOVE_COIL, MOVE_GLARE, MOVE_THOUSAND_ARROWS, MOVE_REST},
            },
            {
                .species = SPECIES_ETERNATUS,
                .heldItem = ITEM_CHOICE_SCARF,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_TIMID,
                .evs = {0, 0, 4, 252, 252, 0},
                .moves = {MOVE_DYNAMAX_CANNON, MOVE_SLUDGE_BOMB, MOVE_FIRE_BLAST, MOVE_TOXIC_SPIKES},
            },
            {
                .species = SPECIES_YVELTAL,
                .heldItem = ITEM_CHOICE_SCARF,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_JOLLY,
                .evs = {32, 0, 252, 224, 0, 0},
                .moves = {MOVE_FOUL_PLAY, MOVE_U_TURN, MOVE_DEFOG, MOVE_TOXIC},
            },
        },
    },
    [FRONTIER_FACILITY_PYRAMID] =
    {
        // Silver Symbol.
        {
            {
                .species = SPECIES_REGIROCK,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = 16,
                .nature = NATURE_IMPISH,
                .evs = {252, 0, 16, 0, 0, 240},
                .moves = {MOVE_STEALTH_ROCK, MOVE_ROCK_BLAST, MOVE_BODY_PRESS, MOVE_IRON_DEFENSE},
            },
            {
                .species = SPECIES_REGICE,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = 16,
                .nature = NATURE_TIMID,
                .evs = {0, 0, 0, 252, 252, 4},
                .moves = {MOVE_FOCUS_BLAST, MOVE_ICE_BEAM, MOVE_THUNDER_WAVE, MOVE_REST},
            },
            {
                .species = SPECIES_REGISTEEL,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = 16,
                .nature = NATURE_IMPISH,
                .evs = {252, 0, 180, 0, 0, 76},
                .moves = {MOVE_STEALTH_ROCK, MOVE_HEAVY_SLAM, MOVE_BODY_PRESS, MOVE_IRON_DEFENSE},
            },
        },
        // Gold Symbol.
        {
            {
                .species = SPECIES_GROUDON,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_IMPISH,
                .evs = {240, 0, 252, 16, 0, 0},
                .moves = {MOVE_SPIKES, MOVE_PRECIPICE_BLADES, MOVE_STONE_EDGE, MOVE_WILL_O_WISP},
            },
            {
                .species = SPECIES_KYOGRE,
                .heldItem = ITEM_CHOICE_SPECS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_MODEST,
                .evs = {248, 0, 0, 44, 216, 0},
                .moves = {MOVE_SURF, MOVE_WATER_SPOUT, MOVE_ICE_BEAM, MOVE_THUNDER},
            },
            {
                .species = SPECIES_RAYQUAZA,
                .heldItem = ITEM_CHOICE_BAND,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_JOLLY,
                .evs = {32, 252, 8, 216, 0, 0},
                .moves = {MOVE_DRAGON_ASCENT, MOVE_U_TURN, MOVE_V_CREATE, MOVE_EXTREME_SPEED},
            },
        },
    },
};
