// Generated by tools/generate_battle_frontier_from_competitive_json.py.
static const struct FrontierBrainMon sFrontierBrainsMons[][2][FRONTIER_PARTY_SIZE] =
{
    [FRONTIER_FACILITY_TOWER] =
    {
        // Silver Symbol.
        {
            {
                .species = SPECIES_LUCARIO,
                .heldItem = ITEM_LUCARIONITE,
                .fixedIV = 24,
                .nature = NATURE_JOLLY,
                .evs = {4, 252, 0, 252, 0, 0},
                .moves = {MOVE_PROTECT, MOVE_CLOSE_COMBAT, MOVE_METEOR_MASH, MOVE_BULLET_PUNCH},
            },
            {
                .species = SPECIES_ALAKAZAM,
                .heldItem = ITEM_FOCUS_SASH,
                .fixedIV = 24,
                .nature = NATURE_TIMID,
                .evs = {0, 0, 4, 252, 252, 0},
                .moves = {MOVE_NASTY_PLOT, MOVE_PSYCHIC, MOVE_FOCUS_BLAST, MOVE_SHADOW_BALL},
            },
            {
                .species = SPECIES_SNORLAX,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = 24,
                .nature = NATURE_IMPISH,
                .evs = {140, 116, 252, 0, 0, 0},
                .moves = {MOVE_PROTECT, MOVE_BELLY_DRUM, MOVE_DOUBLE_EDGE, MOVE_CRUNCH},
            },
        },
        // Gold Symbol.
        {
            {
                .species = SPECIES_LUCARIO,
                .heldItem = ITEM_LUCARIONITE_Z,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_MODEST,
                .evs = {0, 0, 0, 252, 252, 4},
                .moves = {MOVE_AURA_SPHERE, MOVE_STEEL_BEAM, MOVE_DARK_PULSE, MOVE_NASTY_PLOT},
            },
            {
                .species = SPECIES_ENTEI,
                .heldItem = ITEM_HEAVY_DUTY_BOOTS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_JOLLY,
                .evs = {0, 252, 4, 252, 0, 0},
                .moves = {MOVE_EXTREME_SPEED, MOVE_SACRED_FIRE, MOVE_STONE_EDGE, MOVE_TRAILBLAZE},
            },
            {
                .species = SPECIES_RAIKOU,
                .heldItem = ITEM_HEAVY_DUTY_BOOTS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_TIMID,
                .evs = {0, 0, 4, 252, 252, 0},
                .moves = {MOVE_CALM_MIND, MOVE_VOLT_SWITCH, MOVE_SCALD, MOVE_SHADOW_BALL},
            },
        },
    },
    [FRONTIER_FACILITY_DOME] =
    {
        // Silver Symbol.
        {
            {
                .species = SPECIES_CHANDELURE,
                .heldItem = ITEM_CHANDELURITE,
                .fixedIV = 20,
                .nature = NATURE_MODEST,
                .evs = {252, 0, 96, 0, 40, 120},
                .moves = {MOVE_HEAT_WAVE, MOVE_SHADOW_BALL, MOVE_PROTECT, MOVE_TRICK_ROOM},
            },
            {
                .species = SPECIES_SWAMPERT,
                .heldItem = ITEM_SITRUS_BERRY,
                .fixedIV = 20,
                .nature = NATURE_RELAXED,
                .evs = {252, 0, 220, 0, 0, 36},
                .moves = {MOVE_STEALTH_ROCK, MOVE_FLIP_TURN, MOVE_YAWN, MOVE_EARTHQUAKE},
            },
            {
                .species = SPECIES_METAGROSS,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = 20,
                .nature = NATURE_ADAMANT,
                .evs = {252, 28, 0, 188, 0, 40},
                .moves = {MOVE_PSYCHIC_FANGS, MOVE_BULLET_PUNCH, MOVE_ICE_PUNCH, MOVE_PSYCH_UP},
            },
        },
        // Gold Symbol.
        {
            {
                .species = SPECIES_CHANDELURE,
                .heldItem = ITEM_CHANDELURITE,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_MODEST,
                .evs = {252, 0, 96, 0, 40, 120},
                .moves = {MOVE_HEAT_WAVE, MOVE_SHADOW_BALL, MOVE_PROTECT, MOVE_TRICK_ROOM},
            },
            {
                .species = SPECIES_FLUTTER_MANE,
                .heldItem = ITEM_CHOICE_SPECS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_TIMID,
                .evs = {0, 0, 0, 252, 252, 4},
                .moves = {MOVE_SHADOW_BALL, MOVE_MOONBLAST, MOVE_PSYSHOCK, MOVE_POWER_GEM},
            },
            {
                .species = SPECIES_TAPU_FINI,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_BOLD,
                .evs = {252, 0, 64, 192, 0, 0},
                .moves = {MOVE_CALM_MIND, MOVE_SCALD, MOVE_DRAINING_KISS, MOVE_TAUNT},
            },
        },
    },
    [FRONTIER_FACILITY_PALACE] =
    {
        // Silver Symbol.
        {
            {
                .species = SPECIES_EMBOAR,
                .heldItem = ITEM_EMBOARITE,
                .fixedIV = 16,
                .nature = NATURE_ADAMANT,
                .evs = {252, 252, 0, 0, 0, 4},
                .moves = {MOVE_FLARE_BLITZ, MOVE_DRAIN_PUNCH, MOVE_SUCKER_PUNCH, MOVE_PROTECT},
            },
            {
                .species = SPECIES_ARCANINE_HISUI,
                .heldItem = ITEM_FOCUS_SASH,
                .fixedIV = 16,
                .nature = NATURE_JOLLY,
                .evs = {4, 252, 0, 252, 0, 0},
                .moves = {MOVE_FLARE_BLITZ, MOVE_PROTECT, MOVE_HEAD_SMASH, MOVE_EXTREME_SPEED},
            },
            {
                .species = SPECIES_MILOTIC,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = 16,
                .nature = NATURE_CALM,
                .evs = {252, 0, 212, 4, 0, 40},
                .moves = {MOVE_PROTECT, MOVE_SCALD, MOVE_ICY_WIND, MOVE_ICE_BEAM},
            },
        },
        // Gold Symbol.
        {
            {
                .species = SPECIES_EMBOAR,
                .heldItem = ITEM_EMBOARITE,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_ADAMANT,
                .evs = {252, 252, 0, 0, 0, 4},
                .moves = {MOVE_FLARE_BLITZ, MOVE_DRAIN_PUNCH, MOVE_SUCKER_PUNCH, MOVE_PROTECT},
            },
            {
                .species = SPECIES_KARTANA,
                .heldItem = ITEM_CHOICE_SCARF,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_JOLLY,
                .evs = {0, 252, 0, 252, 0, 4},
                .moves = {MOVE_LEAF_BLADE, MOVE_KNOCK_OFF, MOVE_SACRED_SWORD, MOVE_SMART_STRIKE},
            },
            {
                .species = SPECIES_LUGIA,
                .heldItem = ITEM_HEAVY_DUTY_BOOTS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_TIMID,
                .evs = {248, 0, 8, 252, 0, 0},
                .moves = {MOVE_CALM_MIND, MOVE_AIR_SLASH, MOVE_EARTH_POWER, MOVE_RECOVER},
            },
        },
    },
    [FRONTIER_FACILITY_ARENA] =
    {
        // Silver Symbol.
        {
            {
                .species = SPECIES_HERACROSS,
                .heldItem = ITEM_HERACRONITE,
                .fixedIV = 20,
                .nature = NATURE_ADAMANT,
                .evs = {252, 140, 0, 0, 0, 116},
                .moves = {MOVE_CLOSE_COMBAT, MOVE_PIN_MISSILE, MOVE_ROCK_BLAST, MOVE_DETECT},
            },
            {
                .species = SPECIES_KOMMO_O,
                .heldItem = ITEM_LIFE_ORB,
                .fixedIV = 20,
                .nature = NATURE_MODEST,
                .evs = {4, 0, 0, 252, 252, 0},
                .moves = {MOVE_CLANGING_SCALES, MOVE_PROTECT, MOVE_AURA_SPHERE, MOVE_VACUUM_WAVE},
            },
            {
                .species = SPECIES_BRELOOM,
                .heldItem = ITEM_FOCUS_SASH,
                .fixedIV = 20,
                .nature = NATURE_ADAMANT,
                .evs = {4, 252, 0, 252, 0, 0},
                .moves = {MOVE_BULLET_SEED, MOVE_MACH_PUNCH, MOVE_BULLDOZE, MOVE_SPORE},
            },
        },
        // Gold Symbol.
        {
            {
                .species = SPECIES_HERACROSS,
                .heldItem = ITEM_HERACRONITE,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_ADAMANT,
                .evs = {252, 140, 0, 0, 0, 116},
                .moves = {MOVE_CLOSE_COMBAT, MOVE_PIN_MISSILE, MOVE_ROCK_BLAST, MOVE_DETECT},
            },
            {
                .species = SPECIES_HO_OH,
                .heldItem = ITEM_HEAVY_DUTY_BOOTS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_ADAMANT,
                .evs = {252, 252, 0, 4, 0, 0},
                .moves = {MOVE_SACRED_FIRE, MOVE_BRAVE_BIRD, MOVE_RECOVER, MOVE_EARTHQUAKE},
            },
            {
                .species = SPECIES_URSHIFU,
                .heldItem = ITEM_CHOICE_BAND,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_ADAMANT,
                .evs = {0, 252, 4, 252, 0, 0},
                .moves = {MOVE_WICKED_BLOW, MOVE_CLOSE_COMBAT, MOVE_SUCKER_PUNCH, MOVE_U_TURN},
            },
        },
    },
    [FRONTIER_FACILITY_FACTORY] =
    {
        // Silver Symbol.
        {
            {
                .species = SPECIES_KINGAMBIT,
                .heldItem = ITEM_CHOPLE_BERRY,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_ADAMANT,
                .evs = {252, 252, 0, 4, 0, 0},
                .moves = {MOVE_SUCKER_PUNCH, MOVE_KOWTOW_CLEAVE, MOVE_PROTECT, MOVE_IRON_HEAD},
            },
            {
                .species = SPECIES_GARCHOMP,
                .heldItem = ITEM_LIFE_ORB,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_JOLLY,
                .evs = {4, 252, 0, 252, 0, 0},
                .moves = {MOVE_DRAGON_CLAW, MOVE_EARTHQUAKE, MOVE_ROCK_SLIDE, MOVE_PROTECT},
            },
            {
                .species = SPECIES_PINSIR,
                .heldItem = ITEM_PINSIRITE,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_ADAMANT,
                .evs = {244, 196, 0, 64, 0, 4},
                .moves = {MOVE_BODY_SLAM, MOVE_FEINT, MOVE_DETECT, MOVE_PROTECT},
            },
        },
        // Gold Symbol.
        {
            {
                .species = SPECIES_PINSIR,
                .heldItem = ITEM_PINSIRITE,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_ADAMANT,
                .evs = {244, 196, 0, 64, 0, 4},
                .moves = {MOVE_BODY_SLAM, MOVE_FEINT, MOVE_DETECT, MOVE_PROTECT},
            },
            {
                .species = SPECIES_SOLGALEO,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_CAREFUL,
                .evs = {248, 0, 8, 0, 0, 252},
                .moves = {MOVE_KNOCK_OFF, MOVE_ROAR, MOVE_TELEPORT, MOVE_MORNING_SUN},
            },
            {
                .species = SPECIES_XURKITREE,
                .heldItem = ITEM_LIFE_ORB,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_TIMID,
                .evs = {0, 0, 0, 252, 252, 4},
                .moves = {MOVE_DAZZLING_GLEAM, MOVE_ENERGY_BALL, MOVE_VOLT_SWITCH, MOVE_TAIL_GLOW},
            },
        },
    },
    [FRONTIER_FACILITY_PIKE] =
    {
        // Silver Symbol.
        {
            {
                .species = SPECIES_SEVIPER,
                .heldItem = ITEM_LIFE_ORB,
                .fixedIV = 16,
                .nature = NATURE_JOLLY,
                .evs = {0, 252, 0, 252, 0, 4},
                .moves = {MOVE_SUCKER_PUNCH, MOVE_EARTHQUAKE, MOVE_FLAMETHROWER, MOVE_GIGA_DRAIN},
            },
            {
                .species = SPECIES_MILOTIC,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = 16,
                .nature = NATURE_CALM,
                .evs = {252, 0, 212, 4, 0, 40},
                .moves = {MOVE_PROTECT, MOVE_SCALD, MOVE_ICY_WIND, MOVE_ICE_BEAM},
            },
            {
                .species = SPECIES_GLIMMORA,
                .heldItem = ITEM_GLIMMORANITE,
                .fixedIV = 16,
                .nature = NATURE_MODEST,
                .evs = {4, 0, 0, 252, 252, 0},
                .moves = {MOVE_POWER_GEM, MOVE_SLUDGE_BOMB, MOVE_EARTH_POWER, MOVE_SPIKY_SHIELD},
            },
        },
        // Gold Symbol.
        {
            {
                .species = SPECIES_GLIMMORA,
                .heldItem = ITEM_GLIMMORANITE,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_MODEST,
                .evs = {4, 0, 0, 252, 252, 0},
                .moves = {MOVE_POWER_GEM, MOVE_SLUDGE_BOMB, MOVE_EARTH_POWER, MOVE_SPIKY_SHIELD},
            },
            {
                .species = SPECIES_NAGANADEL,
                .heldItem = ITEM_LIFE_ORB,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_TIMID,
                .evs = {0, 0, 0, 252, 252, 4},
                .moves = {MOVE_DRACO_METEOR, MOVE_FIRE_BLAST, MOVE_U_TURN, MOVE_SLUDGE_WAVE},
            },
            {
                .species = SPECIES_YVELTAL,
                .heldItem = ITEM_CHOICE_SCARF,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_JOLLY,
                .evs = {32, 0, 252, 224, 0, 0},
                .moves = {MOVE_FOUL_PLAY, MOVE_U_TURN, MOVE_DEFOG, MOVE_TOXIC},
            },
        },
    },
    [FRONTIER_FACILITY_PYRAMID] =
    {
        // Silver Symbol.
        {
            {
                .species = SPECIES_GOLURK,
                .heldItem = ITEM_GOLURKITE,
                .fixedIV = 16,
                .nature = NATURE_BRAVE,
                .evs = {252, 252, 0, 0, 0, 4},
                .moves = {MOVE_PROTECT, MOVE_POLTERGEIST, MOVE_HEADLONG_RUSH, MOVE_ICE_PUNCH},
            },
            {
                .species = SPECIES_COFAGRIGUS,
                .heldItem = ITEM_SITRUS_BERRY,
                .fixedIV = 16,
                .nature = NATURE_SASSY,
                .evs = {252, 0, 12, 0, 0, 244},
                .moves = {MOVE_TRICK_ROOM, MOVE_BODY_PRESS, MOVE_HEX, MOVE_RAIN_DANCE},
            },
            {
                .species = SPECIES_REGIROCK,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = 16,
                .nature = NATURE_IMPISH,
                .evs = {252, 0, 16, 0, 0, 240},
                .moves = {MOVE_STEALTH_ROCK, MOVE_ROCK_BLAST, MOVE_BODY_PRESS, MOVE_IRON_DEFENSE},
            },
        },
        // Gold Symbol.
        {
            {
                .species = SPECIES_REGIGIGAS,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_JOLLY,
                .evs = {0, 252, 0, 252, 0, 4},
                .moves = {MOVE_DRAIN_PUNCH, MOVE_KNOCK_OFF, MOVE_THUNDER_WAVE, MOVE_RETURN},
            },
            {
                .species = SPECIES_GOLURK,
                .heldItem = ITEM_GOLURKITE,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_BRAVE,
                .evs = {252, 252, 0, 0, 0, 4},
                .moves = {MOVE_PROTECT, MOVE_POLTERGEIST, MOVE_HEADLONG_RUSH, MOVE_ICE_PUNCH},
            },
            {
                .species = SPECIES_REGIROCK,
                .heldItem = ITEM_LEFTOVERS,
                .fixedIV = MAX_PER_STAT_IVS,
                .nature = NATURE_IMPISH,
                .evs = {252, 0, 16, 0, 0, 240},
                .moves = {MOVE_STEALTH_ROCK, MOVE_ROCK_BLAST, MOVE_BODY_PRESS, MOVE_IRON_DEFENSE},
            },
        },
    },
};
